import Link from "next/link";

export const metadata = {
  title: "Terms of Service | Monetra",
  description: "Terms and conditions for using the Monetra AI Finance Planner platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--background)]">
      {/* Header */}
      <div className="border-b border-[var(--border)] bg-[var(--card)]">
        <div className="max-w-3xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="font-serif text-2xl text-[var(--gold)]">Monetra</Link>
          <Link href="/" className="text-xs font-semibold text-[var(--text-muted)] hover:text-[var(--text-main)] transition-colors">← Back to Home</Link>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-12 space-y-8">
        <div>
          <p className="text-[var(--gold)] text-xs font-bold tracking-widest uppercase mb-3">Legal</p>
          <h1 className="font-serif text-4xl text-[var(--text-main)]">Terms of Service</h1>
          <p className="text-[var(--text-muted)] text-sm mt-3">Last updated: March 19, 2025 · Effective immediately</p>
        </div>

        <div className="bg-[var(--card)] border border-[var(--border)] rounded-2xl p-6 space-y-1">
          <p className="text-sm font-bold text-[var(--text-main)]">⚠️ Important Disclaimer</p>
          <p className="text-sm text-[var(--text-sec)] leading-relaxed">
            Monetra is an <strong>educational financial planning tool</strong>. It is NOT a SEBI Registered Investment Advisor (RIA) or a Portfolio Management Service (PMS). All AI-generated investment insights are for informational purposes only and do not constitute personalised investment advice. Please consult a SEBI-registered advisor before making investment decisions.
          </p>
        </div>

        {[
          {
            title: "1. Acceptance of Terms",
            content: `By accessing or using Monetra ("Service," "Platform," "we," "us"), you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree, please do not use the Platform. These terms apply to all visitors, users, and others who access or use the Service.`,
          },
          {
            title: "2. Description of Service",
            content: `Monetra provides AI-powered personal finance planning tools including: investment thesis generation, spending analysis, portfolio tracking, goal planning, and wealth projection. These tools are designed for educational purposes to help Indian retail investors understand financial concepts and options.`,
          },
          {
            title: "3. Not Financial Advice",
            content: `The content generated by Monetra's AI systems — including investment theses, asset allocation suggestions, fund recommendations, and spending audits — is for educational and informational purposes only. It does NOT constitute:
• Personalised investment advice
• A recommendation to buy or sell specific securities
• Asset management or portfolio management services
• Tax advice or legal advice

Monetra is not registered with SEBI as an Investment Advisor, Research Analyst, or any other regulated entity. Historical performance data shown is for illustrative purposes only and does not guarantee future results.`,
          },
          {
            title: "4. User Responsibilities",
            content: `You are responsible for:
• Maintaining the confidentiality of your account credentials
• Ensuring all financial information you provide is accurate
• Making your own independent financial decisions
• Consulting qualified professionals (SEBI RIA, CA, lawyer) before acting on any information from our Platform
• Complying with applicable Indian laws and regulations`,
          },
          {
            title: "5. Subscription and Payments",
            content: `Monetra offers Free and Pro subscription tiers. Pro subscriptions are billed monthly or annually. You may cancel at any time; cancellation takes effect at the end of the current billing period. We do not offer refunds for partial billing periods. Prices are subject to change with 30 days' notice.`,
          },
          {
            title: "6. Data and Privacy",
            content: `We collect financial data you provide (income, expenses, goals, portfolio) to power our AI features. We do not sell your personal financial data to third parties. We comply with India's Digital Personal Data Protection Act (DPDPA) 2023. See our Privacy Policy for full details.`,
          },
          {
            title: "7. Intellectual Property",
            content: `The Monetra platform, its AI models, design, and content are proprietary. You may not copy, distribute, modify, or reverse engineer any part of the platform. User-generated content (expense entries, goal names) remains your property.`,
          },
          {
            title: "8. Limitation of Liability",
            content: `To the maximum extent permitted by law, Monetra and its founders, employees, and affiliates shall not be liable for any financial losses, investment losses, or other damages arising from your use of the Platform or reliance on AI-generated content. Your use of the Platform is entirely at your own risk.`,
          },
          {
            title: "9. Governing Law",
            content: `These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Bangalore, Karnataka, India.`,
          },
          {
            title: "10. Contact",
            content: `For terms-related questions, contact us at legal@monetra.app`,
          },
        ].map((section) => (
          <div key={section.title} className="space-y-3">
            <h2 className="font-bold text-base text-[var(--text-main)]">{section.title}</h2>
            <p className="text-sm text-[var(--text-sec)] leading-relaxed whitespace-pre-line">{section.content}</p>
            <div className="border-b border-[var(--border)]" />
          </div>
        ))}
      </div>
    </div>
  );
}
